name: Deploy to AWS ECS

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin

      - name: Build with Maven
        run: mvn clean package -P test -DskipTests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/propertystore:${{ vars.RELEASE_VERSION }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/propertystore:${{ vars.RELEASE_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.TEST_AWS_REGION }}

      - name: Update ECS service
        run: |
          set -e
          SERVICE_NAME="${{ vars.TEST_ECS_SERVICE_NAME }}"
          CLUSTER_NAME="${{ vars.TEST_ECS_CLUSTER_NAME }}"
          aws ecs update-service \
                --cluster $CLUSTER_NAME \
                --service $SERVICE_NAME \
                --task-definition ${{ vars.TEST_ECS_TASK_NAME }} \
                --force-new-deployment \
                --deployment-configuration "deploymentCircuitBreaker={enable=true,rollback=true}"